/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ciudad.java
 *
 * Created on 13/03/2010, 11:50:59 AM
 */

package trafico;

import javax.swing.JOptionPane;

/**
 *
 * @author Ruco
 */
public class Ciudad extends javax.swing.JFrame {


    public  JOptionPane error = new JOptionPane();

    /** Creates new form Ciudad */
    public Ciudad() {
        initComponents();
      
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new simulacionTrafico();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        horizontalSemaforoUno = new javax.swing.JTextField();
        verticalSemaforoUno = new javax.swing.JTextField();
        cambiarSemaforoUno = new javax.swing.JButton();
        habilitarSemaforoUno = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        horizontalSemaforoDos = new javax.swing.JTextField();
        verticalSemaforoDos = new javax.swing.JTextField();
        cambiarSemaforoDos = new javax.swing.JButton();
        habilitarSemaforoDos = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        horizontalSemaforoTres = new javax.swing.JTextField();
        verticalSemaforoTres = new javax.swing.JTextField();
        cambiarSemaforoTres = new javax.swing.JButton();
        habilitarSemaforoTres = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 472));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Semaforo uno"));

        jLabel1.setText("H");

        jLabel2.setText("V");

        if(jPanel1 instanceof simulacionTrafico ){
            simulacionTrafico sim=(simulacionTrafico)jPanel1;
            Integer tiempo = sim.getTiemposSemaforo(0)[1];
            horizontalSemaforoUno.setText(tiempo.toString());
        }

        if(jPanel1 instanceof simulacionTrafico ){
            simulacionTrafico sim=(simulacionTrafico)jPanel1;
            Integer tiempo = sim.getTiemposSemaforo(0)[0];
            verticalSemaforoUno.setText(tiempo.toString());
        }

        cambiarSemaforoUno.setText("Cambiar");
        cambiarSemaforoUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarSemaforoUnoActionPerformed(evt);
            }
        });

        habilitarSemaforoUno.setText("Encendido");
        habilitarSemaforoUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habilitarSemaforoUnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(habilitarSemaforoUno)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(horizontalSemaforoUno, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(verticalSemaforoUno, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                    .addComponent(cambiarSemaforoUno))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(horizontalSemaforoUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(verticalSemaforoUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cambiarSemaforoUno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(habilitarSemaforoUno)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Semaforo dos"));

        jLabel3.setText("H");

        jLabel4.setText("V");

        if(jPanel1 instanceof simulacionTrafico ){
            simulacionTrafico sim=(simulacionTrafico)jPanel1;
            Integer tiempo = sim.getTiemposSemaforo(1)[1];
            horizontalSemaforoDos.setText(tiempo.toString());
        }

        if(jPanel1 instanceof simulacionTrafico ){
            simulacionTrafico sim=(simulacionTrafico)jPanel1;
            Integer tiempo = sim.getTiemposSemaforo(1)[0];
            verticalSemaforoDos.setText(tiempo.toString());
        }

        cambiarSemaforoDos.setText("Cambiar");
        cambiarSemaforoDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarSemaforoDosActionPerformed(evt);
            }
        });

        habilitarSemaforoDos.setText("Encendido");
        habilitarSemaforoDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habilitarSemaforoDosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(habilitarSemaforoDos)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(horizontalSemaforoDos, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(verticalSemaforoDos, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                    .addComponent(cambiarSemaforoDos))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(horizontalSemaforoDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(verticalSemaforoDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cambiarSemaforoDos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(habilitarSemaforoDos)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Semaforo tres"));

        jLabel5.setText("H");

        jLabel6.setText("V");

        if(jPanel1 instanceof simulacionTrafico ){
            simulacionTrafico sim=(simulacionTrafico)jPanel1;
            Integer tiempo = sim.getTiemposSemaforo(2)[1];
            horizontalSemaforoTres.setText(tiempo.toString());
        }

        if(jPanel1 instanceof simulacionTrafico ){
            simulacionTrafico sim=(simulacionTrafico)jPanel1;
            Integer tiempo = sim.getTiemposSemaforo(2)[0];
            verticalSemaforoTres.setText(tiempo.toString());
        }

        cambiarSemaforoTres.setText("Cambiar");
        cambiarSemaforoTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarSemaforoTresActionPerformed(evt);
            }
        });

        habilitarSemaforoTres.setText("Encendido");
        habilitarSemaforoTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habilitarSemaforoTresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(habilitarSemaforoTres)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(horizontalSemaforoTres, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(verticalSemaforoTres, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                    .addComponent(cambiarSemaforoTres))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(horizontalSemaforoTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(verticalSemaforoTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cambiarSemaforoTres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(habilitarSemaforoTres)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensajes"));

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        simulacionTrafico sim=(simulacionTrafico)jPanel1;
        sim.agregarTextArea(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Pausar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarSemaforoUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarSemaforoUnoActionPerformed
        try{
            int tiempoH=Integer.parseInt(this.horizontalSemaforoUno.getText());
            int tiempoV=Integer.parseInt(this.verticalSemaforoUno.getText());
            if(jPanel1 instanceof simulacionTrafico){
               // System.out.println("algo");
                simulacionTrafico sim=(simulacionTrafico)jPanel1;
                sim.cambiarTiempoSemaforo(0, tiempoH*1000, tiempoV*1000);
            }
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Los valores deben ser numeros enteros positivos", "ADVERTENCIA",  JOptionPane.WARNING_MESSAGE);

        }
        
    }//GEN-LAST:event_cambiarSemaforoUnoActionPerformed

    private void habilitarSemaforoUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habilitarSemaforoUnoActionPerformed
       try{
        if(jPanel1 instanceof simulacionTrafico){
           // System.out.println("algo");
            simulacionTrafico sim=(simulacionTrafico)jPanel1;
             if(habilitarSemaforoUno.isSelected()){
                sim.encenderSemaforo(0);
             }else{
                sim.apagarSemaforo(0);
             }
        }
       
        }catch (NumberFormatException e){
                        JOptionPane.showMessageDialog(null, "Los valores deben ser numeros enteros positivos", "ADVERTENCIA",  JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_habilitarSemaforoUnoActionPerformed

    private void cambiarSemaforoDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarSemaforoDosActionPerformed
      try{
        int tiempoH=Integer.parseInt(this.horizontalSemaforoDos.getText());
        int tiempoV=Integer.parseInt(this.verticalSemaforoDos.getText());
        if(jPanel1 instanceof simulacionTrafico){
           // System.out.println("algo");
            simulacionTrafico sim=(simulacionTrafico)jPanel1;
            sim.cambiarTiempoSemaforo(1, tiempoH*1000, tiempoV*1000);
        }
      } catch (NumberFormatException e){
             JOptionPane.showMessageDialog(null, "Los valores deben ser numeros enteros positivos", "ADVERTENCIA",  JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_cambiarSemaforoDosActionPerformed

    private void habilitarSemaforoDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habilitarSemaforoDosActionPerformed
        if(jPanel1 instanceof simulacionTrafico){
           // System.out.println("algo");
            simulacionTrafico sim=(simulacionTrafico)jPanel1;
             if(habilitarSemaforoDos.isSelected()){
                sim.encenderSemaforo(1);
             }else{
                sim.apagarSemaforo(1);
             }
        }
    }//GEN-LAST:event_habilitarSemaforoDosActionPerformed

    private void cambiarSemaforoTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarSemaforoTresActionPerformed
        try{
            int tiempoH=Integer.parseInt(this.horizontalSemaforoTres.getText());
            int tiempoV=Integer.parseInt(this.verticalSemaforoTres.getText());
            if(jPanel1 instanceof simulacionTrafico){
               // System.out.println("algo");
                simulacionTrafico sim=(simulacionTrafico)jPanel1;
               sim.cambiarTiempoSemaforo(2, tiempoH*1000, tiempoV*1000);
            }
        }
        catch (NumberFormatException e){
             JOptionPane.showMessageDialog(null, "Los valores deben ser numeros enteros positivos", "ADVERTENCIA",  JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_cambiarSemaforoTresActionPerformed

    private void habilitarSemaforoTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habilitarSemaforoTresActionPerformed
        if(jPanel1 instanceof simulacionTrafico){
            simulacionTrafico sim=(simulacionTrafico)jPanel1;
            if(habilitarSemaforoTres.isSelected()){
                sim.encenderSemaforo(2);
            }
            else{
                sim.apagarSemaforo(2);
            }
        }
    }//GEN-LAST:event_habilitarSemaforoTresActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        simulacionTrafico sim = (simulacionTrafico)jPanel1;
        sim.pausarJuego();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ciudad().setVisible(true);
               
            }
        });


    }

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarSemaforoDos;
    private javax.swing.JButton cambiarSemaforoTres;
    private javax.swing.JButton cambiarSemaforoUno;
    private javax.swing.JCheckBox habilitarSemaforoDos;
    private javax.swing.JCheckBox habilitarSemaforoTres;
    private javax.swing.JCheckBox habilitarSemaforoUno;
    private javax.swing.JTextField horizontalSemaforoDos;
    private javax.swing.JTextField horizontalSemaforoTres;
    private javax.swing.JTextField horizontalSemaforoUno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField verticalSemaforoDos;
    private javax.swing.JTextField verticalSemaforoTres;
    private javax.swing.JTextField verticalSemaforoUno;
    // End of variables declaration//GEN-END:variables
 
}
